package com.kp.composearc.presentation.viewmodels

import androidx.lifecycle.ViewModel

class ListViewScreenViewModel : ViewModel(){
    val fruits = listOf(
        Fruit("Apple", "https://en.wikipedia.org/wiki/Apple",
            "https://upload.wikimedia.org/wikipedia/commons/1/15/Red_Apple.jpg",
            "A sweet, crisp fruit often red, green, or yellow in color."),
        Fruit("Banana", "https://en.wikipedia.org/wiki/Banana",
            "https://upload.wikimedia.org/wikipedia/commons/8/8a/Banana-Single.jpg",
            "A soft, sweet fruit with a yellow peel, rich in potassium."),
        Fruit("Mango", "https://en.wikipedia.org/wiki/Mango",
            "https://upload.wikimedia.org/wikipedia/commons/9/90/Hapus_Mango.jpg",
            "A tropical stone fruit known for its juicy, sweet flesh."),
        Fruit("Orange", "https://en.wikipedia.org/wiki/Orange_(fruit)",
            "https://upload.wikimedia.org/wikipedia/commons/c/c4/Orange-Fruit-Pieces.jpg",
            "A citrus fruit known for its bright color and tangy flavor."),
        Fruit("Grapes", "https://en.wikipedia.org/wiki/Grape",
            "https://upload.wikimedia.org/wikipedia/commons/4/40/Table_grapes_on_white.jpg",
            "Small, sweet berries that grow in clusters and can be eaten fresh or used in wine."),
        Fruit("Pineapple", "https://en.wikipedia.org/wiki/Pineapple",
            "https://upload.wikimedia.org/wikipedia/commons/c/cb/Pineapple_and_cross_section.jpg",
            "A tropical fruit with a spiky exterior and sweet, tangy flesh."),
        Fruit("Watermelon", "https://en.wikipedia.org/wiki/Watermelon",
            "https://upload.wikimedia.org/wikipedia/commons/f/fd/Watermelon_cross_BNC.jpg",
            "A large, juicy fruit with green rind and sweet red flesh."),
        Fruit("Papaya", "https://en.wikipedia.org/wiki/Papaya",
            "https://upload.wikimedia.org/wikipedia/commons/7/7b/Papaya_cross_section.jpg",
            "A tropical fruit with sweet orange flesh and black seeds."),
        Fruit("Strawberry", "https://en.wikipedia.org/wiki/Strawberry",
            "https://upload.wikimedia.org/wikipedia/commons/2/29/PerfectStrawberry.jpg",
            "A small, red fruit with a juicy texture and sweet flavor."),
        Fruit("Blueberry", "https://en.wikipedia.org/wiki/Blueberry",
            "https://upload.wikimedia.org/wikipedia/commons/0/05/Blueberries.jpg",
            "Small, round berries with a sweet-tart taste and deep blue color."),
        Fruit("Raspberry", "https://en.wikipedia.org/wiki/Raspberry",
            "https://upload.wikimedia.org/wikipedia/commons/8/8d/Raspberry_pi.jpg",
            "A soft, red berry with a sweet-tart taste."),
        Fruit("Cherry", "https://en.wikipedia.org/wiki/Cherry",
            "https://upload.wikimedia.org/wikipedia/commons/b/bb/Cherry_Stella444.jpg",
            "A small, round stone fruit with sweet or sour flavor."),
        Fruit("Peach", "https://en.wikipedia.org/wiki/Peach",
            "https://upload.wikimedia.org/wikipedia/commons/9/9e/Autumn_Red_peach.jpg",
            "A soft, juicy fruit with fuzzy skin and sweet flavor."),
        Fruit("Plum", "https://en.wikipedia.org/wiki/Plum",
            "https://upload.wikimedia.org/wikipedia/commons/f/f5/Plums.jpg",
            "A small stone fruit with smooth skin and sweet or tart taste."),
        Fruit("Pear", "https://en.wikipedia.org/wiki/Pear",
            "https://upload.wikimedia.org/wikipedia/commons/0/0f/Pears.jpg",
            "A sweet fruit with a soft, grainy texture."),
        Fruit("Kiwi", "https://en.wikipedia.org/wiki/Kiwifruit",
            "https://upload.wikimedia.org/wikipedia/commons/d/d3/Kiwi_aka.jpg",
            "A small, fuzzy brown fruit with bright green, tangy flesh."),
        Fruit("Pomegranate", "https://en.wikipedia.org/wiki/Pomegranate",
            "https://upload.wikimedia.org/wikipedia/commons/0/07/Pomegranate.jpg",
            "A fruit filled with juicy, ruby-red seeds."),
        Fruit("Dragon Fruit", "https://en.wikipedia.org/wiki/Pitaya",
            "https://upload.wikimedia.org/wikipedia/commons/e/ee/Pitaya_cross_section_ed2.jpg",
            "An exotic cactus fruit with vibrant skin and sweet, mild flesh."),
        Fruit("Guava", "https://en.wikipedia.org/wiki/Guava",
            "https://upload.wikimedia.org/wikipedia/commons/a/a4/Guava_ID.jpg",
            "A tropical fruit with green skin and pink or white sweet flesh."),
        Fruit("Lychee", "https://en.wikipedia.org/wiki/Lychee",
            "https://upload.wikimedia.org/wikipedia/commons/0/05/Litchi_chinensis_fruits.JPG",
            "A small fruit with rough red skin and juicy white interior."),
        Fruit("Apricot", "https://en.wikipedia.org/wiki/Apricot",
            "https://upload.wikimedia.org/wikipedia/commons/7/7b/Apricots.jpg",
            "A small, golden-orange fruit with smooth skin and sweet flesh."),
        Fruit("Blackberry", "https://en.wikipedia.org/wiki/Blackberry",
            "https://upload.wikimedia.org/wikipedia/commons/5/59/Blackberries.jpg",
            "A dark, juicy berry with a sweet and tart taste."),
        Fruit("Cantaloupe", "https://en.wikipedia.org/wiki/Cantaloupe",
            "https://upload.wikimedia.org/wikipedia/commons/3/36/Cantaloupe_and_cross_section.jpg",
            "A sweet melon with orange flesh and a netted rind."),
        Fruit("Fig", "https://en.wikipedia.org/wiki/Common_fig",
            "https://upload.wikimedia.org/wikipedia/commons/1/19/Figs_on_tree.jpg",
            "A small, sweet fruit with soft skin and many seeds."),
        Fruit("Gooseberry", "https://en.wikipedia.org/wiki/Gooseberry",
            "https://upload.wikimedia.org/wikipedia/commons/c/c1/Gooseberries.jpg",
            "A small, tart berry that can be green, red, or purple."),
        Fruit("Jackfruit", "https://en.wikipedia.org/wiki/Jackfruit",
            "https://upload.wikimedia.org/wikipedia/commons/f/f2/Jackfruit_hanging.JPG",
            "A massive tropical fruit with sweet, fibrous yellow pods."),
        Fruit("Lemon", "https://en.wikipedia.org/wiki/Lemon",
            "https://upload.wikimedia.org/wikipedia/commons/c/c5/Lemon.jpg",
            "A bright yellow citrus fruit known for its sour flavor."),
        Fruit("Lime", "https://en.wikipedia.org/wiki/Lime_(fruit)",
            "https://upload.wikimedia.org/wikipedia/commons/c/c4/Limes.jpg",
            "A small green citrus fruit with tart juice."),
        Fruit("Passion Fruit", "https://en.wikipedia.org/wiki/Passiflora_edulis",
            "https://upload.wikimedia.org/wikipedia/commons/b/b8/Passion_fruit_and_cross_section.jpg",
            "A tropical fruit with a wrinkly purple skin and tangy pulp."),
        Fruit("Persimmon", "https://en.wikipedia.org/wiki/Persimmon",
            "https://upload.wikimedia.org/wikipedia/commons/c/c8/Persimmon.jpg",
            "A sweet, orange fruit with a smooth texture when ripe.")
    )
}

data class Fruit(
    val name: String,
    val url: String,
    val imageUrl: String,
    val description: String
)

